version: 1
blog_frontend_version: 1
blog_api_version: 1
settings:
  - blog_code: "GREENPOWERGURU"
    blog_name: "Green Power Guru"
    blog_title: "Green Power Insights"
    blog_subtitle: "Your Daily Dose of Renewable Energy Expertise"
    blog_url: "https://www.example.com"
    blog_logo_file: "blog_logo.webp"
    blog_logo_file_alt_text: ""
    blog_description: "Green Power Guru offers the latest news, in-depth analyses, and innovative ideas in the field of renewable energy. From solar panels to wind farms and beyond, discover how renewable technologies are transforming our world, one watt at a time."
external_platforms:
  - external_platform_code: "FACEBBOKCOM"
    external_platform_nametag: "example"
    external_platform_share_post_enabled: true
    external_platform_is_visible: true
  - external_platform_code: "INSTAGRAMCOM"
    external_platform_nametag: "example"
    external_platform_share_post_enabled: true
    external_platform_is_visible: true
  - external_platform_code: "TIKTOK"
    external_platform_nametag: "example"
    external_platform_share_post_enabled: true
    external_platform_is_visible: true
  - external_platform_code: "XCOM"
    external_platform_nametag: "example"
    external_platform_share_post_enabled: true
    external_platform_is_visible: true
  - external_platform_code: "PINTERESTCOM"
    external_platform_nametag: "example"
    external_platform_share_post_enabled: true
    external_platform_is_visible: true
  - external_platform_code: "SNAPCHATCOM"
    external_platform_nametag: "example"
    external_platform_share_post_enabled: true
    external_platform_is_visible: true
  - external_platform_code: "LINKEDINCOM"
    external_platform_nametag: "example"
    external_platform_share_post_enabled: true
    external_platform_is_visible: true
  - external_platform_code: "BLOGSPOTCOM"
    external_platform_nametag: "example"
    external_platform_share_post_enabled: true
    external_platform_is_visible: true
  - external_platform_code: "REDDITCOM"
    external_platform_nametag: "example"
    external_platform_share_post_enabled: true
    external_platform_is_visible: true
  - external_platform_code: "WYKOPPL"
    external_platform_nametag: "example"
    external_platform_share_post_enabled: true
    external_platform_is_visible: true
  - external_platform_code: "GITHUBCOM"
    external_platform_nametag: "example"
    external_platform_share_post_enabled: true
    external_platform_is_visible: true
includes:
  - include_file_name: "header_announcement_0.md"
    include_is_visible: true
    include_embedded_files: []
  - include_file_name: "header_announcement_1.md"
    include_is_visible: true
    include_embedded_files: []
  - include_file_name: "page_contact_0.md"
    include_is_visible: true
    include_embedded_files: []
  - include_file_name: "page_privacypolicy_0.md"
    include_is_visible: true
    include_embedded_files: 
      - file_name: "example_1.webp"
        file_alt_text: ""
  - include_file_name: "page_terms_0.md"
    include_is_visible: true
    include_embedded_files: 
      - file_name: "example_1.webp"
        file_alt_text: ""
  - include_file_name: "sidebar_ad_0.md"
    include_is_visible: true
    include_embedded_files: 
      - file_name: "example_1.webp"
        file_alt_text: ""
      - file_name: "example_2.webp"
        file_alt_text: ""
  - include_file_name: "sidebar_ad_1.md"
    include_is_visible: true
    include_embedded_files: 
      - file_name: "example_1.webp"
        file_alt_text: ""