version: 1
settings:
  - blog_name: "Green Power Guru"
    blog_title: "Green Power Insights"
    blog_subtitle: "Your Daily Dose of Renewable Energy Expertise"
    blog_url: "https://www.example.com"
    blog_logo_file: "logo.webp"
    blog_description: "Green Power Guru offers the latest news, in-depth analyses, and innovative ideas in the field of renewable energy. From solar panels to wind farms and beyond, discover how renewable technologies are transforming our world, one watt at a time."
    blog_frontend_type: 1
categories:
  - category_code: "SOLAR"
    category: "Solar Energy"
  - category_code: "WIND"
    category: "Wind Power"
  - category_code: "HYDRO"
    category: "Hydroelectric Power"
  - category_code: "GEOTHERMAL"
    category: "Geothermal Energy"
  - category_code: "BIOMASS"
    category: "Biomass and Biofuels"
  - category_code: "STORAGE"
    category: "Energy Storage"
  - category_code: "POLICY"
    category: "Policy and Regulations"
  - category_code: "MARKET"
    category: "Market Trends"
  - category_code: "INNOVATION"
    category: "Innovations in Technology"
  - category_code: "SUSTAINABILITY"
    category: "Sustainability and Environment"
social_media:
  - name: "facebook.com"
    nametag: "example"
    full_url: "https://facebook.com/example"
    allow_share: true
    is_visible: true
  - name: "instagram.com"
    nametag: "example"
    full_url: "https://instagram.com/example"
    allow_share: true
    is_visible: true
  - name: "x.com"
    nametag: "example"
    full_url: "https://x.com/example"
    allow_share: true
    is_visible: true
