version: 1
settings:
  - blog_code: "GREENPOWERGURU"
    blog_name: "Green Power Guru"
    blog_title: "Green Power Insights"
    blog_subtitle: "Your Daily Dose of Renewable Energy Expertise"
    blog_url: "https://www.example.com"
    blog_logo_file: "blog_logo.webp"
    blog_description: "Green Power Guru offers the latest news, in-depth analyses, and innovative ideas in the field of renewable energy. From solar panels to wind farms and beyond, discover how renewable technologies are transforming our world, one watt at a time."
    visible_external_platforms: ["FACEBBOKCOM", "XCOM"]
    visible_external_platforms_nametags: ["example", "example"]
    allow_share_external_platforms: ["FACEBBOKCOM", "XCOM"]
    allow_share_external_platforms_nametags: ["example", "example"]
    blog_frontend_version: 1
    blog_api_version: 1
